language: java
script: gradle build
install:
- chmod +x gradle
deploy:
  provider: releases
  file: 
  - build/libs/EDM-${TRAVIS_BUILD_NUMBER}.jar
  skip_cleanup: true
  on:
   tags: true
   all_branches: true