/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edminstallerjp;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/**
 *
 * @author Zach
 */
public class MainWindow extends java.awt.Frame {

    public String InstallLocation="null";
    public String RunLocation = System.getProperty("user.dir");
    public File Source = new File(RunLocation + "/EDM.jar");
    public Path SourcePath = Source.toPath();
    public File Output = new File(InstallLocation+ "/mods/EDM.jar");
    public Path OutputPath = Output.toPath();
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        Json.genDefaults();
        Json.instance.run();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void initComponents() {

        FinderDialog = new javax.swing.JFileChooser();
       InstallButton = new javax.swing.JButton();
        EDMCheck = new java.awt.Checkbox();
        ForgeCheck = new java.awt.Checkbox();
        InstallPath = new java.awt.TextField();
        Finder = new java.awt.Button();

        FinderDialog.setApproveButtonText("Ok");
        FinderDialog.setApproveButtonToolTipText("");
        FinderDialog.setBackground(java.awt.Color.white);
        FinderDialog.setCurrentDirectory(new File(System.getenv("appdata") + "/.minecraft"));
        FinderDialog.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        FinderDialog.setMinimumSize(new java.awt.Dimension(500, 320));
        FinderDialog.setName("Finder"); // NOI18N
        FinderDialog.setPreferredSize(new java.awt.Dimension(500, 320));
        FinderDialog.getAccessibleContext().setAccessibleName("FinderDialog");
        FinderDialog.getAccessibleContext().setAccessibleDescription("");

        setBackground(java.awt.Color.white);
        setBounds(new java.awt.Rectangle(0, 0, 320, 140));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setName("EDMInstaller"); // NOI18N
        setSize(new java.awt.Dimension(320, 140));
        setTitle("EDM Installer For Minecraft 1.7.10");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InstallButton.setActionCommand("InstallButton");
        InstallButton.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        InstallButton.setText("Install");
        InstallButton.setName("InstallButton"); // NOI18N
        InstallButton.setPreferredSize(new java.awt.Dimension(75, 20));
        InstallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstallButtonActionPerformed(evt);
            }
        });
        add(InstallButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 75, 20));
        InstallButton.getAccessibleContext().setAccessibleName("");
        EDMCheck.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        EDMCheck.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        EDMCheck.setLabel("Extra Diamonds Mod Version 4.1.0");
        EDMCheck.setMinimumSize(new java.awt.Dimension(220, 20));
        EDMCheck.setName("EDMCheck"); // NOI18N
        EDMCheck.setPreferredSize(new java.awt.Dimension(0, 0));
        EDMCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                EDMCheckItemStateChanged(evt);
            }
        });
        add(EDMCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 220, 20));
        EDMCheck.getAccessibleContext().setAccessibleName("EDMCheck");

        ForgeCheck.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        ForgeCheck.setLabel("MinecraftForge Version 1291");
        ForgeCheck.setMinimumSize(new java.awt.Dimension(180, 20));
        ForgeCheck.setName("ForgeCheck"); // NOI18N
        ForgeCheck.setPreferredSize(new java.awt.Dimension(0, 0));
        ForgeCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ForgeCheckItemStateChanged(evt);
            }
        });
        add(ForgeCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 180, 20));
        ForgeCheck.getAccessibleContext().setAccessibleName("ForgeCheck");

        InstallPath.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        InstallPath.setEditable(false);
        InstallPath.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        InstallPath.setMinimumSize(new java.awt.Dimension(240, 20));
        InstallPath.setName("InstallPath"); // NOI18N
        InstallPath.setPreferredSize(new java.awt.Dimension(0, 0));
        InstallPath.setText("Find Path");
        add(InstallPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 240, 20));
        InstallPath.getAccessibleContext().setAccessibleName("InstallPath");

        Finder.setActionCommand("FinderButton");
        Finder.setLabel("...");
        Finder.setMinimumSize(new java.awt.Dimension(25, 20));
        Finder.setName("Finder"); // NOI18N
        Finder.setPreferredSize(new java.awt.Dimension(0, 0));
        Finder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinderActionPerformed(evt);
            }
        });
        add(Finder, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 25, 20));
        Finder.getAccessibleContext().setAccessibleName("FinderButton");

        getAccessibleContext().setAccessibleName("MainWindow");
        getAccessibleContext().setAccessibleDescription("");
    }

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void EDMCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_EDMCheckItemStateChanged
        // TODO add your handling code here:
        if(EDMCheck.getState()==true){
            Json.es.setvalue("true");
            System.out.println(Json.es.getvalue());
            try {
                Json.instance.run();
            } catch (Exception ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            Json.es.setvalue("false");
            System.out.println(Json.es.getvalue());
            try {
                Json.instance.run();
            } catch (Exception ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_EDMCheckItemStateChanged

    private void ForgeCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ForgeCheckItemStateChanged
    if (ForgeCheck.getState()==true)
    {
        Json.config.setvalue("true");
        Json.instance.run();
        System.out.println(Json.config.getvalue().toString());
    }
     else
    {
        Json.config.setvalue("false");
        Json.instance.run();
        System.out.println(Json.config.getvalue().toString());
    }
    }//GEN-LAST:event_ForgeCheckItemStateChanged

    private void FinderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinderActionPerformed
        // TODO add your handling code here:
        FinderDialog.showDialog(this, "ok");
        InstallLocation= FinderDialog.getSelectedFile().toString();
        InstallPath.setText(InstallLocation);
    }//GEN-LAST:event_FinderActionPerformed

    private void InstallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstallButtonActionPerformed
        // TODO add your handling code here:
        if (Json.es.getvalue()=="true")
        {
            System.out.println("It Worked!!!");
            if (!(new File(System.getProperty("user.dir") + "/EDM.jar")).exists())
            {
                DownloadFiles.download("http://addons-origin.cursecdn.com/files/2237/271/[1.7.10]EDM-4.1.0-Universal.jar", "EDM-4.1.0-Universal.jar");
            }
            else
            {
                System.out.println("Already Downloaded. Moving file...");
            }
            if (!(new File(InstallLocation + "/mods/EDM.jar")).exists())
            {
                try {
                    Files.move(SourcePath,OutputPath ,REPLACE_EXISTING);
                } catch (IOException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
            {
                System.out.println("Mod is already installed");
            }
        }
        else
        {
            System.out.println("Oops!! Something went wrong!! " + Json.es.getname().toString() + " was not vaild or the config was tampered with, so no install happened.");
        }
        if (Json.config.getvalue()== "true")
        {
            DownloadFiles.download("http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.2.1291/forge-1.7.10-10.13.2.1291-installer-win.exe", "forge.exe");
            if((new File(System.getProperty("user.dir") + "/forge.exe")).exists()){
                ProcessBuilder proc = new ProcessBuilder("forge.exe");
                try {
                    proc.start();
                    //System.Process.Start(System.getProperty("user.dir") + "/forge.exe");
                } catch (IOException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else
        {
            System.out.println("Oops!! Something went wrong!!");
        }
    }//GEN-LAST:event_InstallButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    //javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
                    UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    java.awt.Checkbox EDMCheck;
    java.awt.Button Finder;
    javax.swing.JFileChooser FinderDialog;
    java.awt.Checkbox ForgeCheck;
    javax.swing.JButton InstallButton;
    java.awt.TextField InstallPath;
}
